server:
    port: 9191

spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            routes:
                - id: USER-SERVICE
                  uri: lb://USER-SERVICE
                  predicates:
                  - Path=/users/**
                - id: DEPARTMENT-SERVICE
                  uri: lb://DEPARTMENT-SERVICE
                  predicates:
                  - Path=/departments/**

eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost 